version: 2 # use CircleCI 2.0
workflows:
  workflow:
    jobs:
      - build:
          name: build <<matrix.version>>
          matrix:
            parameters:
              version: ["1.13", "1.14"]
          docker: # run the steps with Docker
            # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
            - image: circleci/golang:<<matrix.version>> #
            # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/

          environment: # environment variables for the build itself
            TEST_RESULTS: /tmp/test-results # path to where test results will be saved

          steps: # steps that comprise the `build` job
            - checkout # check out source code to working directory
            - run: mkdir -p $TEST_RESULTS # create the test results directory

            - restore_cache: # restores saved cache if no changes are detected since last run
                # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
                keys:
                  - v1-pkg-cache

            - run: go get github.com/jstemmer/go-junit-report
            - run: make deps

            - run:
                name: Run unit tests
                # Store the results of our tests in the $TEST_RESULTS directory
                command: |
                  trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
                  make test | tee ${TEST_RESULTS}/go-test.out

      #      - run: make # pull and build dependencies for the project

            - save_cache: # Store cache in the /go/pkg directory
                key: v1-pkg-cache
                paths:
                  - "/go/pkg"

            - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
                path: /tmp/test-results
                destination: raw-test-output

            - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
                path: /tmp/test-results